'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';

type Json = Record<string, unknown>;
const money = (value: unknown) => `৳${Number(value || 0).toLocaleString('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function errorOf(payload: Json) { const errors = payload.errors as Record<string, string[]> | undefined; return errors ? Object.values(errors).flat()[0] : typeof payload.message === 'string' ? payload.message : 'The request could not be completed.'; }

export function AffiliatePanel({ initiallyAuthenticated }: { initiallyAuthenticated: boolean }) {
  const [authenticated, setAuthenticated] = useState(initiallyAuthenticated), [mode, setMode] = useState<'login'|'register'>('login');
  const [dashboard, setDashboard] = useState<Json | null>(null), [view, setView] = useState('dashboard'), [records, setRecords] = useState<Json[]>([]);
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const call = useCallback(async (resource: string, options: RequestInit = {}) => { const response = await fetch(`/api/affiliate/${resource}`, { headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, ...options }); const payload = await response.json() as Json; if (!response.ok || payload.status !== 'success') throw new Error(errorOf(payload)); return payload.data as Json; }, []);
  const loadDashboard = useCallback(async () => { try { setDashboard(await call('dashboard')); setMessage(''); } catch (error) { setMessage((error as Error).message); if ((error as Error).message.includes('session')) setAuthenticated(false); } }, [call]);
  useEffect(() => { if (!authenticated) return; const timer = window.setTimeout(() => void loadDashboard(), 0); return () => window.clearTimeout(timer); }, [authenticated, loadDashboard]);
  async function auth(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { if (mode === 'register' && values.password !== values.password_confirmation) throw new Error('Passwords do not match.'); await call(mode, { method: 'POST', body: JSON.stringify(values) }); if (mode === 'login') setAuthenticated(true); else { setMode('login'); setMessage('Registration submitted. Sign in after an administrator approves the account.'); } } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function open(resource: string) { setView(resource); setBusy(true); try { const data = await call(resource); const value = data[resource] as { data?: Json[] } | Json[] | undefined; setRecords(Array.isArray(value) ? value : value?.data || []); setMessage(''); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function mutation(event: FormEvent<HTMLFormElement>, resource: string) { event.preventDefault(); setBusy(true); try { await call(resource, { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); event.currentTarget.reset(); setMessage(resource === 'transfer' ? 'Balance transferred successfully.' : 'Withdrawal request submitted.'); await loadDashboard(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  async function logout() { try { await call('logout', { method: 'POST', body: '{}' }); } finally { setAuthenticated(false); setDashboard(null); } }
  if (!authenticated) return <main className="affiliate-auth"><section><Link href="/" className="content-logo">Jaba9</Link><p className="content-eyebrow">Affiliate centre</p><h1>{mode === 'login' ? 'Affiliate sign in' : 'Affiliate application'}</h1><form onSubmit={auth}>{mode === 'register' && <><input name="name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email" required/><input name="phone" placeholder="Phone" required/></>}<input name="username" placeholder="Username or email" required/><input name="password" type="password" minLength={6} placeholder="Password" required/>{mode === 'register' && <input name="password_confirmation" type="password" minLength={6} placeholder="Confirm password" required/>}<p aria-live="polite">{message}</p><button disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Submit application'}</button></form><button className="affiliate-switch" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage(''); }}>{mode === 'login' ? 'Apply as an affiliate' : 'Already approved? Sign in'}</button></section></main>;
  const widget = (dashboard?.widget || {}) as Json, affiliate = (dashboard?.affiliate || {}) as Json;
  return <main className="affiliate-app"><header><div><Link href="/" className="content-logo">Jaba9</Link><p>Affiliate Centre</p></div><button onClick={logout}>Sign out</button></header><nav aria-label="Affiliate navigation"><button onClick={() => setView('dashboard')}>Overview</button>{['users','deposits','earnings','withdrawals'].map(item => <button key={item} onClick={() => void open(item)}>{item}</button>)}</nav><section className="affiliate-body"><p className="content-eyebrow">Welcome, {String(affiliate.name || affiliate.username || 'Affiliate')}</p>{message && <p className="affiliate-message" aria-live="polite">{message}</p>}{view === 'dashboard' ? <><div className="affiliate-stats">{[['Referred users',widget.referred_users],['Deposited users',widget.deposited_users],['Referred deposits',money(widget.referred_deposit_total)],['Commission balance',money(widget.commission_balance)],['Total earned',money(widget.total_earned)],['Pending withdrawal',money(widget.pending_withdraw)]].map(([label,value]) => <article key={String(label)}><span>{String(label)}</span><strong>{String(value ?? '—')}</strong></article>)}</div><label className="affiliate-referral">Referral link<input readOnly value={String(dashboard?.referral_link || '')}/></label><div className="affiliate-forms"><form onSubmit={event => void mutation(event,'transfer')}><h2>Transfer to referred user</h2><input name="username" placeholder="Referred username" required/><input name="amount" inputMode="decimal" placeholder="Amount (minimum 100)" required/><button disabled={busy}>Transfer</button></form><form onSubmit={event => void mutation(event,'withdraw')}><h2>Request withdrawal</h2><input name="amount" inputMode="decimal" placeholder="Amount" required/><input name="payment_method" placeholder="Payment method" required/><textarea name="withdraw_information" placeholder="Destination/account information" required/><button disabled={busy}>Submit request</button></form></div></> : <div className="affiliate-records"><h1>{view[0].toUpperCase()+view.slice(1)}</h1>{busy ? <p role="status">Loading…</p> : records.length ? records.map((record,index) => <article key={String(record.id || index)}><strong>{String(record.username || record.subject || record.trx || `Record ${index + 1}`)}</strong><span>{record.amount === undefined ? String(record.email || record.created_at || '') : money(record.amount)}</span></article>) : <p>No records found.</p>}</div>}</section></main>;
}
