export type PublicPage = { title: string; eyebrow: string; description: string; sections: { heading: string; body: string }[] };

export const publicPages: Record<string, PublicPage> = {
  games: { title: 'All Games', eyebrow: 'Game catalogue', description: 'Browse the current game catalogue by category and provider from the homepage.', sections: [{ heading: 'Find a game', body: 'Return to the catalogue and use the category and provider filters. Only games enabled by the operator are displayed.' }] },
  cricket: { title: 'Cricket', eyebrow: 'Sports', description: 'Discover cricket titles and live-event products offered by enabled providers.', sections: [{ heading: 'Availability', body: 'Fixtures, odds and game availability come from the active provider catalogue and may change without notice.' }] },
  casino: { title: 'Live Casino', eyebrow: 'Live games', description: 'Explore enabled live dealer and casino games in one place.', sections: [{ heading: 'Play responsibly', body: 'Set a budget before playing. Never chase losses and stop when play is no longer enjoyable.' }] },
  slot: { title: 'Slot Games', eyebrow: 'Casino games', description: 'Browse slot games from active providers using the catalogue filters.', sections: [{ heading: 'Game information', body: 'Rules, return information and limits are shown by the applicable game provider before play.' }] },
  sportsbook: { title: 'Sportsbook', eyebrow: 'Sports', description: 'Access supported sports products and current events from active providers.', sections: [{ heading: 'Event settlement', body: 'Provider rules govern event grading, voids, postponements and settlement. Review them before placing a wager.' }] },
  fishing: { title: 'Fishing Games', eyebrow: 'Arcade', description: 'Find enabled fishing and arcade-style games from the public catalogue.', sections: [{ heading: 'Device support', body: 'Use a current browser and a stable connection. Availability can vary by device and provider.' }] },
  crash: { title: 'Crash Games', eyebrow: 'Instant games', description: 'Browse available crash-style games and review each game’s rules before playing.', sections: [{ heading: 'Risk reminder', body: 'Outcomes are uncertain. Decide your limit in advance and never use essential funds.' }] },
  promotion: { title: 'Promotions', eyebrow: 'Offers', description: 'Current offers are shown only when enabled by the operator.', sections: [{ heading: 'Before you join', body: 'Check minimum deposit, eligible games, maximum bonus, turnover, expiry and withdrawal conditions for each offer.' }] },
  'jayarank/challenge': { title: 'Rewards & Challenges', eyebrow: 'Loyalty', description: 'Track eligible rewards and challenge information published by the operator.', sections: [{ heading: 'Eligibility', body: 'Reward availability and progress depend on the published promotion rules and verified account activity.' }] },
  register: { title: 'Create an Account', eyebrow: 'Get started', description: 'Registration is available from the secure modal on the homepage.', sections: [{ heading: 'Account safety', body: 'Use accurate information and a unique password. Never share your password, OTP or payment receipt with another person.' }] },
  faq: { title: 'Frequently Asked Questions', eyebrow: 'Help centre', description: 'Answers to common account, deposit, withdrawal and game questions.', sections: [{ heading: 'Deposits and withdrawals', body: 'Available methods and limits appear after sign-in. A deposit is credited only after verified settlement; withdrawals may require identity and destination checks.' }, { heading: 'Account access', body: 'Use password recovery from the sign-in form. Support will never ask for your password or one-time code.' }] },
  contact: { title: 'Contact Support', eyebrow: 'Help centre', description: 'Signed-in customers can open and track support tickets from their account.', sections: [{ heading: 'Urgent payment issue', body: 'Include the transaction reference, time and method. Do not send passwords, OTPs, full card details or secret credentials.' }, { heading: 'Response tracking', body: 'Keep the request ID shown with an error so support can locate the related server event.' }] },
  terms: { title: 'Terms & Conditions', eyebrow: 'Legal', description: 'These platform terms apply together with promotion and provider-specific rules.', sections: [{ heading: 'Eligibility and lawful use', body: 'You must be at least 18 and legally permitted to use the service where you are located. The service must not be used to evade local restrictions.' }, { heading: 'Account and funds', body: 'Keep account details secure and accurate. Deposits, withdrawals, bonuses, reversals and event settlement follow the published method and promotion rules.' }, { heading: 'Fair use', body: 'Fraud, collusion, payment abuse, multiple-account abuse and attempts to interfere with the platform are prohibited and may be investigated.' }] },
  privacy: { title: 'Privacy Policy', eyebrow: 'Legal', description: 'This summary explains how account and service data should be handled.', sections: [{ heading: 'Data collected', body: 'The service may process identity, contact, device, login, transaction, support and legally required verification information.' }, { heading: 'Use and protection', body: 'Data is used to operate accounts, prevent abuse, process transactions, meet legal duties and provide support. Access should be limited and logged.' }, { heading: 'Your choices', body: 'Contact support for applicable access, correction or deletion requests. Financial and security records may require statutory retention.' }] },
  'responsible-gaming': { title: 'Responsible Gaming', eyebrow: 'Player protection', description: 'Gaming should remain entertainment and must never threaten essential spending or wellbeing.', sections: [{ heading: 'Stay in control', body: 'Set time and spending limits, take regular breaks, never chase losses and do not borrow to gamble.' }, { heading: 'Get help', body: 'If play feels difficult to control, stop, use available account limits or exclusion tools, and contact an appropriate independent support service in your jurisdiction.' }, { heading: 'Under 18', body: 'This service is not for minors. Guardians should use device-level controls and protect payment and account credentials.' }] },
  cookies: { title: 'Cookie Policy', eyebrow: 'Legal', description: 'Cookies support sign-in, security preferences and essential platform operation.', sections: [{ heading: 'Essential cookies', body: 'Authentication, security and consent cookies are required for core features. Optional analytics or marketing cookies should be used only with appropriate consent.' }] },
  about: { title: 'About JUBO88', eyebrow: 'Company', description: 'JUBO88 is the operator-facing brand presented by this application.', sections: [{ heading: 'Platform boundary', body: 'Laravel owns identity, balances and transaction records. The web application communicates with those services through narrowly scoped same-origin routes.' }] },
};

export const publicNav = [
  ['Home', '/'], ['Games', '/games'], ['Cricket', '/cricket'], ['Live Casino', '/casino'], ['Slots', '/slot'],
  ['Sports', '/sportsbook'], ['Fishing', '/fishing'], ['Crash', '/crash'], ['Promotions', '/promotion'], ['Help', '/faq'],
] as const;
